.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SCHEME-R5RS 1 "April 16, 2005"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
scheme-r5rs \- Run a Scheme script in an R5RS environment
.SH SYNOPSIS
.B scheme-r5rs
.RI program-file " arguments" ...
.SH DESCRIPTION

This command runs a Scheme script from the command line. It will load
the Scheme script given in
.B program-file
into an R5RS environment and call the
.B main
procedure with the
.B arguments
as a single list of strings.

.SH SEE ALSO
.BR scheme-srfi-7.scheme48 (1),
.br
.BR SRFI 22 " (http://srfi.schemers.org/srfi-22/srfi-22.html)"

.SH AUTHORS
.B scheme-r5rs
for Scheme48 was written by Richard Kelsey and Jonathan Rees.
.BR
This manual page was written by Jorgen Schaefer <forcer@debian.org>,
for the Debian project (but may be used by others).
